
import { CarListing } from './types';

export const MAKES = [
  'Porsche', 'Ferrari', 'Lamborghini', 'McLaren', 'Aston Martin', 
  'Rolls-Royce', 'Bentley', 'Mercedes-AMG', 'BMW M', 'Ford GT', 'Chevrolet', 'Lucid'
];

export const REGIONS = [
  'Downtown Toronto', 'Vaughan', 'Oakville', 'Mississauga', 'Richmond Hill', 'Markham'
];

export const RARITY_KEYWORDS = [
  'PTS', 'Weissach', 'Manual', 'Carbon Ceramics', 'Track Package', 
  'Low Miles', 'CPO', 'Full Leather', 'Exclusive Manufaktur', 'OTA-Ready'
];

export const MOCK_LISTINGS: CarListing[] = [
  {
    id: '1',
    title: '2022 Porsche 911 GT3 (Shark Blue)',
    make: 'Porsche',
    model: '911 GT3',
    year: 2022,
    trim: 'PDK',
    odometer: 5000,
    price: 315000,
    location: 'Vaughan, ON',
    region: 'Vaughan',
    dealerName: 'Pfaff Porsche',
    originalUrl: 'https://www.autotrader.ca/placeholder1',
    imageUrl: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&q=80&w=1200',
    description: 'Launch color Shark Blue. Collector grade mileage. Full front PPF. Steel brakes, 18-way seats.',
    vibeScore: 97,
    aiInsights: ['Hero Color Premium', 'Collector Grade Miles', 'High US Demand'],
    rarityKeywords: ['Low Miles', 'OTA-Ready'],
    usExportProfitCad: 45000,
    vin: 'WP0AF2A97PS28xxxx', // W = Germany
    isExportSuitable: true,
    cpoStatus: true,
    hiddenSoftwareValueCad: 8500,
    recallStatus: 'Clear',
    daysToTurnGta: 18,
    daysToTurnUs: 9,
    vehicleHealthScore: 98,
    monthlyPaymentCad: 4850,
    priceDelta7d: -2.4,
    scrapeTimestamp: new Date().toISOString(),
    priceHistory: [{ date: '2024-01-01', price: 325000 }, { date: '2024-02-15', price: 315000 }]
  },
  {
    id: '2',
    title: '2020 Ford GT Heritage Edition',
    make: 'Ford GT',
    model: 'Heritage',
    year: 2020,
    trim: 'Carbon',
    odometer: 1200,
    price: 1250000,
    location: 'Oakville, ON',
    region: 'Oakville',
    dealerName: 'Legendary Motorcar',
    originalUrl: 'https://www.autotrader.ca/placeholder2',
    imageUrl: 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&q=80&w=1200',
    description: 'Ken Miles Heritage livery. 1 of 50. US-Made powerhouse returning home.',
    vibeScore: 85,
    aiInsights: ['US-Made Zero Tariff', 'Highest Margin Flip', 'Investment Grade'],
    rarityKeywords: ['Low Miles', 'Heritage'],
    usExportProfitCad: 220000,
    vin: '1FA6P8CF0L5xxxx', // 1 = USA (Zero Tariff)
    isExportSuitable: true,
    cpoStatus: false,
    hiddenSoftwareValueCad: 0,
    recallStatus: 'Clear',
    daysToTurnGta: 60,
    daysToTurnUs: 5,
    vehicleHealthScore: 100,
    monthlyPaymentCad: 14500,
    priceDelta7d: 0.0,
    scrapeTimestamp: new Date().toISOString(),
    priceHistory: [{ date: '2024-03-01', price: 1250000 }]
  },
  {
    id: '3',
    title: '2023 Ferrari 296 GTB',
    make: 'Ferrari',
    model: '296 GTB',
    year: 2023,
    trim: 'Assetto Fiorano',
    odometer: 800,
    price: 485000,
    location: 'Downtown Toronto, ON',
    region: 'Downtown Toronto',
    dealerName: 'Ferrari of Ontario',
    originalUrl: 'https://www.autotrader.ca/placeholder3',
    imageUrl: 'https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&q=80&w=1200',
    description: 'Bianco Cervino. Assetto Fiorano pack. Carbon wheels.',
    vibeScore: 92,
    aiInsights: ['Assetto Fiorano Pack', 'Hybrid Efficiency', 'New Model Demand'],
    rarityKeywords: ['Track Package'],
    usExportProfitCad: 62000,
    vin: 'ZFF89ALA1P0xxxx', // Z = Italy
    isExportSuitable: true,
    cpoStatus: true,
    hiddenSoftwareValueCad: 5000,
    recallStatus: 'Clear',
    daysToTurnGta: 35,
    daysToTurnUs: 12,
    vehicleHealthScore: 96,
    monthlyPaymentCad: 7200,
    priceDelta7d: -0.5,
    scrapeTimestamp: new Date().toISOString(),
    priceHistory: [{ date: '2024-02-01', price: 485000 }]
  },
  {
    id: '4',
    title: '2024 Chevrolet Corvette Z06 3LZ',
    make: 'Chevrolet',
    model: 'Corvette Z06',
    year: 2024,
    trim: 'Z07 Performance',
    odometer: 150,
    price: 215000,
    location: 'Mississauga, ON',
    region: 'Mississauga',
    dealerName: 'Holand Automotive',
    originalUrl: 'https://www.autotrader.ca/placeholder4',
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=1200',
    description: 'Torch Red. Full Z07 aero package. Carbon fiber wheels. US-Made powerhouse eligible for 0% duty return.',
    vibeScore: 89,
    aiInsights: ['Zero-Tariff Eligible', 'High Resale in Florida/TX', 'Z07 Package Rarity'],
    rarityKeywords: ['Track Package', 'US-Made'],
    usExportProfitCad: 35000,
    vin: '1G1Y62D4XRYxxxx', // 1 = USA (Zero Tariff)
    isExportSuitable: true,
    cpoStatus: false,
    hiddenSoftwareValueCad: 2200,
    recallStatus: 'Clear',
    daysToTurnGta: 22,
    daysToTurnUs: 8,
    vehicleHealthScore: 99,
    monthlyPaymentCad: 3200,
    priceDelta7d: 1.2,
    scrapeTimestamp: new Date().toISOString(),
    priceHistory: [{ date: '2024-04-01', price: 215000 }]
  },
  {
    id: '5',
    title: '2023 Lamborghini Huracán Sterrato',
    make: 'Lamborghini',
    model: 'Huracán Sterrato',
    year: 2023,
    trim: 'V10 AWD',
    odometer: 450,
    price: 498000,
    location: 'Vaughan, ON',
    region: 'Vaughan',
    dealerName: 'Grand Touring Autos',
    originalUrl: 'https://www.autotrader.ca/placeholder5',
    imageUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&q=80&w=1200',
    description: 'Limited production off-road supercar. Verde Gea finish. Rally lights and roof rack included.',
    vibeScore: 94,
    aiInsights: ['Limited Run # of 1499', 'High Auction Interest', 'Unique Spec'],
    rarityKeywords: ['Exclusive Manufaktur', 'Low Miles'],
    usExportProfitCad: 58000,
    vin: 'ZHWU4DRS0PLAxxxx', // Z = Italy
    isExportSuitable: true,
    cpoStatus: true,
    hiddenSoftwareValueCad: 4500,
    recallStatus: 'Clear',
    daysToTurnGta: 40,
    daysToTurnUs: 15,
    vehicleHealthScore: 97,
    monthlyPaymentCad: 8100,
    priceDelta7d: 0.0,
    scrapeTimestamp: new Date().toISOString(),
    priceHistory: [{ date: '2024-03-10', price: 498000 }]
  },
  {
    id: '6',
    title: '2021 McLaren 765LT Spider',
    make: 'McLaren',
    model: '765LT',
    year: 2021,
    trim: 'Spider',
    odometer: 2100,
    price: 645000,
    location: 'Downtown Toronto, ON',
    region: 'Downtown Toronto',
    dealerName: 'McLaren Toronto',
    originalUrl: 'https://www.autotrader.ca/placeholder6',
    imageUrl: 'https://images.unsplash.com/photo-1621135802920-133df287f89c?auto=format&fit=crop&q=80&w=1200',
    description: '1 of 765 globally. MSO Defined Ceramic Grey. Roof Scoop and Full Carbon exterior pack.',
    vibeScore: 91,
    aiInsights: ['MSO Bespoke Spec', 'Track Focused Appreciator', 'Spider Premium'],
    rarityKeywords: ['Carbon Ceramics', 'Low Miles'],
    usExportProfitCad: 72000,
    vin: 'SBM13BCDXMAxxxx', // S = UK
    isExportSuitable: true,
    cpoStatus: true,
    hiddenSoftwareValueCad: 12000,
    recallStatus: 'Clear',
    daysToTurnGta: 45,
    daysToTurnUs: 20,
    vehicleHealthScore: 95,
    monthlyPaymentCad: 11000,
    priceDelta7d: -1.8,
    scrapeTimestamp: new Date().toISOString(),
    priceHistory: [{ date: '2024-01-20', price: 658000 }, { date: '2024-04-12', price: 645000 }]
  },
  {
    id: '7',
    title: '2023 Lucid Air Sapphire',
    make: 'Lucid',
    model: 'Air Sapphire',
    year: 2023,
    trim: 'Sapphire',
    odometer: 850,
    price: 325000,
    location: 'Richmond Hill, ON',
    region: 'Richmond Hill',
    dealerName: 'Lucid Toronto',
    originalUrl: 'https://www.autotrader.ca/placeholder7',
    imageUrl: 'https://images.unsplash.com/photo-1669272338308-5f2129759495?auto=format&fit=crop&q=80&w=1200',
    description: '1,200+ HP EV Masterpiece. US-Made in Arizona. Zero-Tariff eligible for US return.',
    vibeScore: 82,
    aiInsights: ['Zero-Tariff Return', 'OTA Performance Ready', 'Hyper-Sedan Niche'],
    rarityKeywords: ['OTA-Ready', 'US-Made'],
    usExportProfitCad: 42000,
    vin: '5GRY62XDXPAxxxx', // 5 = USA (Zero Tariff)
    isExportSuitable: true,
    cpoStatus: false,
    hiddenSoftwareValueCad: 15000,
    recallStatus: 'Clear',
    daysToTurnGta: 28,
    daysToTurnUs: 6,
    vehicleHealthScore: 100,
    monthlyPaymentCad: 5200,
    priceDelta7d: 0.5,
    scrapeTimestamp: new Date().toISOString(),
    priceHistory: [{ date: '2024-05-01', price: 325000 }]
  },
  {
    id: '8',
    title: '2022 Mercedes-AMG GT Black Series',
    make: 'Mercedes-AMG',
    model: 'GT Black Series',
    year: 2022,
    trim: 'Black Series',
    odometer: 1800,
    price: 585000,
    location: 'Markham, ON',
    region: 'Markham',
    dealerName: 'Mercedes-Benz Markham',
    originalUrl: 'https://www.autotrader.ca/placeholder8',
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&q=80&w=1200',
    description: 'AMG Magno Orange. Track record holder spec. Full carbon aero.',
    vibeScore: 95,
    aiInsights: ['Nürburgring Record Spec', 'Collector Final Edition', 'Strong Germany Demand'],
    rarityKeywords: ['Track Package', 'Carbon Ceramics'],
    usExportProfitCad: 65000,
    vin: 'W1K456DMXLAxxxx', // W = Germany
    isExportSuitable: true,
    cpoStatus: true,
    hiddenSoftwareValueCad: 6000,
    recallStatus: 'Clear',
    daysToTurnGta: 30,
    daysToTurnUs: 14,
    vehicleHealthScore: 98,
    monthlyPaymentCad: 9400,
    priceDelta7d: 0.0,
    scrapeTimestamp: new Date().toISOString(),
    priceHistory: [{ date: '2024-02-15', price: 585000 }]
  }
];
